default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: <%= ENV.fetch("DB_TIMEOUT") { 5000 } %>

development:
  <<: *default
  database: mat_views_db_dev
  username: dev
  password: dev

test:
  <<: *default
  database: mat_views_db_test
  username: test
  password: test

production:
  <<: *default
  database: mat_views_app_db
